version: '3'

services:
  app:
    build:
      context: .
      args:
        VARIANT: '3.1-bullseye'
        BUNDLER_VERSION: '2.3.14'
        RAILS_VERSION: '7.0.3'
        NODE_VERSION: '16'
    environment:
      BINDING: 0.0.0.0
    volumes:
      - .:/usr/src/app  
      - bundle-volume:/usr/local/bundle
    ports:
      - "3000:3000"
    working_dir: /usr/src/app  
    command: ["rails", "server", "-b", "0.0.0.0"]
volumes:
  bundle-volume:
