version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1

jobs:
  create_tag:
    docker:
      - image: circleci/python:3.8  # 適宜イメージを選択
    steps:
      - checkout
      - run:
          name: Create Git Tag
          command: |
            git config --global user.email "your-email@example.com"
            git config --global user.name "Your Name"
            git tag -a v$(date +'%Y%m%d%H%M%S') -m "Tagging from CircleCI"
            git push origin --tags

  test-ruby:
    docker:
      - image: cimg/ruby:3.2.4-node
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: rails test
          command: bundle exec rails test

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

workflows:
  version: 2
  tag_workflow:
    jobs:
      - create_tag:
          filters:
            branches:
              only: main  # タグを作成するブランチを指定

  build-and-test:
    jobs:
      - test-ruby
    # - deploy:
    #     requires:
    #       - test-ruby
